# Generated by Django 4.0.3 on 2022-05-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0002_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTP',
            new_name='OTP_TOTP',
        ),
    ]
