# Generated by Django 4.0.3 on 2022-05-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0003_rename_otp_otp_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_totp',
            name='confirmed',
            field=models.BooleanField(default=True, help_text='Is this device ready for use?'),
        ),
    ]
